services:
  next-app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WATCHPACK_POLLING_INTERVAL=300
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
  mysql:
    image: mysql:latest
    container_name: exam_summer_2025_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exam_summer_2025
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3300:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: exam_summer_2025_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80

volumes:
  mysql_data:
