services:
  next-app:
    build:
      context: .
    ports:
      - "3000:3000"
  mysql:
    image: mysql:latest
    container_name: exam_summer_2025_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exam_summer_2025
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3300:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: exam_summer_2025_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80

volumes:
  mysql_data:
