import { Libre_Franklin } from "next/font/google";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import { SideBar } from "@/components/SideBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarRight from "@/components/SidebarRight";
import { Toaster } from "sonner";

const libreFranklin = Libre_Franklin({
  variable: "--font-libre-franklin",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${libreFranklin.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="overflow-x-hidden flex justify-center">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeWrapper>
            <div className="max-w-5xl flex">
              <header className="">
                <SidebarProvider>
                  <SideBar />
                </SidebarProvider>
              </header>
              {children}
              <SidebarRight />
            </div>
            <Toaster />
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
