import { Libre_Franklin } from "next/font/google";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import { SideBar } from "@/components/SideBar";
import { SidebarProvider } from "@/components/ui/sidebar";

const libreFranklin = Libre_Franklin({
  variable: "--font-libre-franklin",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${libreFranklin.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="overflow-x-hidden">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeWrapper>
            <div className="max-w-5xl grid grid-cols-[auto_1fr_auto] mx-auto">
              <header>
                <SidebarProvider>
                  <SideBar />
                </SidebarProvider>
              </header>
              {children}
            </div>
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
