import { Geist, Geist_Mono } from "next/font/google";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import { SideBar } from "@/components/SideBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="grid grid-cols-[auto_1fr_auto]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeWrapper>
            <SidebarProvider>
              <SideBar />
            </SidebarProvider>
            {children}
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
